---

- name: Main playbook execution
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Update package list
      raw: apt-get update
    - name: Ensure Python3 is installed on managed hosts
      raw: test -e /usr/bin/python3 || (apt-get install -y python3)
    - name: Gather facts
      setup:

- name: Import preparation playbook
  import_playbook: "{{ lookup('env','ANSIBLE_HOME') }}/playbooks/preparation/config_ubuntu.yml"
