MASTER_COUNT = 1
MASTER_MEMORY = 512
MASTER_CPU = 1
MASTER_HOSTNAME_PREFIX = "k3smaster"

WORKER_COUNT = 0
WORKER_MEMORY = 1500
WORKER_CPU = 1
WORKER_HOSTNAME_PREFIX = "k3snode"

COUNTER = 0
BOX = "alpine/alpine64"

Vagrant.configure("2") do |config|
  # Creation of the master nodes
  (1..MASTER_COUNT).each do |machine_id|
    config.vm.define "#{MASTER_HOSTNAME_PREFIX}0#{machine_id}" do |machine|
      machine.vm.box = "#{BOX}"
      machine.ssh.insert_key = false
      COUNTER = COUNTER + 1
      machine.vm.hostname = "#{MASTER_HOSTNAME_PREFIX}0#{COUNTER}"
      machine.vm.network "private_network", ip: "10.0.15.#{38 + COUNTER}"
      machine.vm.network "forwarded_port", guest: 22, host: "22#{36 + COUNTER}", id: "ssh"
      machine.ssh.forward_agent = true
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.post_up_message = "Counter = #{COUNTER}"
      machine.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", "#{MASTER_MEMORY}"]
        v.customize ["modifyvm", :id, "--cpus", "#{MASTER_CPU}"]
      end
    end
  end

  # Creation of the worker nodes
  (1..WORKER_COUNT).each do |machine_id|
    config.vm.define "#{WORKER_HOSTNAME_PREFIX}0#{machine_id}" do |machine|
      machine.vm.box = "#{BOX}"
      machine.ssh.insert_key = false
      COUNTER = COUNTER + 1
      machine.vm.hostname = "#{WORKER_HOSTNAME_PREFIX}0#{COUNTER}"
      machine.vm.network "private_network", ip: "10.0.15.#{38 + COUNTER}"
      machine.vm.network "forwarded_port", guest: 22, host: "22#{36 + COUNTER}", id: "ssh"
      machine.ssh.forward_agent = true
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", "#{WORKER_MEMORY}"]
        v.customize ["modifyvm", :id, "--cpus", "#{WORKER_CPU}"]
      end
    end
  end

  #config.vm.provision :ansible do |ansible|
  #  ansible.limit = "all"
  #  ansible.config_file = "provisioning/ansible.cfg"
  #  #ansible.inventory_path = "provisioning/inventory/hosts.ini"
  #  ansible.playbook = "provisioning/site.yml"
  #end
end
