Vagrant.require_version ">= 1.6.0"

Vagrant.configure("2") do |config|
  # create first node first
  config.vm.define "worker01" do |machine|
    machine.vm.box = "generic/rhel7"
    machine.ssh.guest_port = 2222
    machine.ssh.insert_key = false
    machine.vm.hostname = "worker01"
    machine.vm.network "private_network", type: "dhcp"
    machine.ssh.forward_agent = true
    machine.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
    end
    machine.vm.provision :ansible do |ansible|
      ansible.limit = "all"
      ansible.config_file = "provisioning/ansible.cfg"
      ansible.inventory_path = "provisioning/inventory/hosts.ini"
      ansible.playbook = "provisioning/site.yml"
    end
  end
end
