---

- hosts: all
  force_handlers: yes
  tasks:
    - name: a task which always notifies its handler
      command: /bin/true
      notify: restart the web server
    - name: a task which fails because the package doesn't exist
      service:
        name: httpd
        state: started
  handlers:
    - name: restart the web server
      service:
        name: httpd
        state: restarted
