---

- name: Use archiving
  hosts: all
  gather_facts: yes
  tasks:
    - name: Create a file to archive
      file:
        state: touch
        path: /tmp/database_list.txt
        owner: root
        group: root
    - name: Add data to file
      lineinfile:
        path: /tmp/database_list.txt
        line: "dev,test,qa,prod"
    - name: Archive the file
      archive:
        path: /tmp/database_list.txt
        dest: /tmp/database_list.gz
