---

- name: Gather facts
  setup:

- name: add IP address of all hosts to /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }} {{ item }}"
    state: present
  loop: "{{ groups['all'] }}"

#- name: Update all packages
#  dnf:
#    name: '*'
#    state: latest
#    update_cache: yes

- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes

- name: Install required packages
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ required_packages }}"
