Vagrant.require_version ">= 1.6.0"

NODE_COUNT = 1
MEMORY = 1024
CPU = 1

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |machine_id|
    config.vm.define "node0#{machine_id}" do |machine|
      # TODO: upgrade base box to the latest version on your local
      machine.vm.box = "generic/rhel8"
      machine.ssh.insert_key = false
      machine.vm.hostname = "node0#{machine_id}"
      machine.vm.network "private_network", ip: "10.0.15.#{25+machine_id}"
      machine.vm.network "forwarded_port", guest: 22, host: "22#{10+machine_id}", id: "ssh"
      machine.ssh.forward_agent = true
      machine.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", "#{MEMORY}"]
        v.customize ["modifyvm", :id, "--cpus", "#{CPU}"]
      end
      if machine_id == NODE_COUNT
        machine.vm.provision :ansible do |ansible|
          ansible.limit = "all"
          ansible.config_file = "provisioning/ansible.cfg"
          ansible.inventory_path = "provisioning/inventory/hosts.ini"
          ansible.playbook = "provisioning/site.yml"
        end
      end
    end
  end
end
