---

- name: Pause 5 seconds before running rest of zookeeper handlers
  pause:
    seconds: 5

- name: Reload firewalld for zookeeper service
  command: firewall-cmd --reload

- name: Start and enable zookeeper service
  service:
    name: zookeeper
    enabled: yes
    state: started

- name: Create a symlink of zookeeper log directory
  file:
    src: "{{ link_path }}/logs"
    dest: "{{ log_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: link
