---

- name: add IP address of all hosts to /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }} {{ item }}"
    state: present
  loop: "{{ groups['all'] }}"

- name: Ensure firewalld is started and enabled
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Set timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"

- name: Import tasks to continue with yum
  import_tasks: redhat7.yml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"
  tags:
  - redhat7

- name: Import tasks to continue with dnf
  import_tasks: redhat8.yml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"
  tags:
  - redhat8
