Vagrant.configure("2") do |config|
  # configure our atomic host
  config.vm.define "fedora-atomic" do |node|
    node.vm.box = "fedora/29-atomic-host"
    node.ssh.insert_key = false
    node.vm.hostname = "fedora-atomic"
    node.ssh.forward_agent = true
    node.vm.network "private_network", ip: "10.0.15.10"
    node.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", "2048"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end
  end
end
